### ISSUE TITLE
Missing rustybam dependency in conda env

### ISSUE THREAD

**Issue by koisland** [mrvollger/asm-to-reference-alignment#1]
Hi,

I've been building a pipeline using this pipeline as a module. Many of the rules use [`bioconda::rustybam`](https://anaconda.org/bioconda/rustybam) and it looks to be missing from [`workflow/env/env.yaml` ](https://github.com/mrvollger/asm-to-reference-alignment/blob/main/workflow/envs/env.yml) file. 

https://github.com/mrvollger/asm-to-reference-alignment/blob/fe0d4d5f1ccfd28bc1e3d926df83d64f18047e92/workflow/rules/reference_alignment.smk#L164-L169

```yaml
name: smk
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - minimap2>=2.24.0
  - samtools>=1.13
  - htslib>=1.13
  - bcftools>=1.13
  - pysam
  - bedtools>=2.30.0
  - pybedtools
  - pigz
  - seqtk
  - numba
  - numpy
  - pandas
  - csvtk
  - ucsc-bedtobigbed
  - ucsc-bedgraphtobigwig
  - networkx
```

So, when any of these rules are run, the pipeline fails.
```bash
Activating conda environment: .snakemake/conda/9c61c373740d0b8509c2bed8700eb25f_
/usr/bin/bash: line 2: rb: command not found
[Wed Jan 17 13:39:26 2024]
Error in rule ref_align_aln_to_bed:
    jobid: 4
    input: results/t2t_chm13_v2.0/bam/HG00171_1.bam
    output: results/t2t_chm13_v2.0/bed/HG00171_1.bed
    conda-env: /home/keith/Projects/hgsvc3/.snakemake/conda/9c61c373740d0b8509c2bed8700eb25f_
    shell:
        
        rb --threads 1 stats results/t2t_chm13_v2.0/bam/HG00171_1.bam > results/t2t_chm13_v2.0/bed/HG00171_1.bed
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)
```

Would it be okay if I opened a PR to fix this?

Thanks,
Keith
